
data_preprocess:
  total_days: "0-23"
  train_days: "0-22"
  test_days: "23-23"
  input_folder: "hdfs://sr133:9000/dlrm/input/"
  test_input_folder: "hdfs://sr133:9000/dlrm/test/"
  output_folder: "hdfs://sr133:9000/dlrm/output/"
  model_size_file: True
  model_folder: "hdfs://sr133:9000/dlrm/model/"
  write_mode: overwrite
  dict_build_shuffle_parallel_per_day: 2
  low_mem: False
  frequency_limit: 15
  spark_config:
    app_name: "dlrm"
    num_executors: 8
    executor_cores: 15
    executor_memory: 120GB
    configs:
      spark.local.dir: "/mnt/DP_disk1/xianyang/spark,/mnt/DP_disk2/xianyang/spark,/mnt/DP_disk3/xianyang/spark,/mnt/DP_disk4/xianyang/spark"
      spark.network.timeout: 1800s
      spark.driver.memory: 100GB
      spark.sql.files.maxPartitionBytes: 1073741824
      spark.driver.maxResultSize: 10G
      spark.locality.wait: 1s
      spark.sql.autoBroadcastJoinThreshold: 500M
      spark.sql.broadcastTimeout: 1800s
      spark.sql.shuffle.partitions: 600
      spark.executor.extraJavaOptions: "-XX:+UseParallelGC -XX:+UseParallelOldGC -XX:+UseAdaptiveSizePolicy"

mpi_config:
  env:
    KMP_BLOCKTIME: 1
    KMP_AFFINITY: "granularity=fine,compact,1,0"
    LD_PRELOAD: "/home/xianyang/sw/miniconda3/envs/test/lib/libtcmalloc.so"
    CCL_WORKER_COUNT: 4
    CCL_WORKER_AFFINITY: "0,1,2,3,24,25,26,27,"
    CCL_ATL_TRANSPORT: ofi
    OMP_NUM_THREADS: 20
  I_MPI_PIN_DOMAIN: "[0xfffff0,0xfffff0000000,]"
  job_name: dlrm
  world_size: 4
  num_cpus_per_process: 1
  num_processes_per_node: 2
  timeout: 5
  mpi_type: intel_mpi

model_arguments:
  dist_backend: ccl
  sparse_dense_boundary: 2048
  bf16: True
  use_ipex: True
  arch_dense_feature_size: 13
  arch_sparse_feature_size: 128
  arch_mlp_bot: "13-512-256-128"
  arch_mlp_top: "1024-1024-512-256-1"
  max_ind_range: 40000000
  loss_function: bce
  round_targets: True
  learning_rate: 18.0
  mini_batch_size: 32768
  test_mini_batch_size: 65536
  print_freq: 128
  print_time: True
  test_freq: 6400
  lr_num_warmup_steps: 8000
  lr_decay_start_step: 70000
  lr_num_decay_steps: 30000
  mlperf_logging: True
  mlperf_auc_threshold: 0.8025
  mlperf_bin_shuffle: True
  numpy_rand_seed: 12345
  data_generation: dataset
  data_set: terabyte
  memory_map: True
  processed_data_file: "/mnt/DP_disk5/spark_preproc/dst/terabyte_processed.npz"
  mlperf_bin_loader: True
  enable_profiling: False
  nepochs: 1
